name             'bcpc'
maintainer       'Bloomberg Finance L.P.'
maintainer_email 'hadoop@bloomberg.net'
license          'Apache License 2.0'
description      'Installs/Configures Bloomberg Clustered Private Cloud (BCPC)'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt'
depends 'bfd'
depends 'bach_repository'
depends 'build-essential'
depends 'chef-client'
# https://github.com/bloomberg/chef-bach/issues/873
#depends 'chef-vault'
depends 'chef-vault', '=1.3.3'
depends 'cobblerd'
depends 'cron'
depends 'database'
depends 'graphite_handler'
depends 'line'
depends 'nscd'
depends 'ntp'
depends 'python'
depends 'ubuntu'
depends 'sudo'
depends 'pdns'
