# vim: tabstop=2:shiftwidth=2:softtabstop=2 
default['hadoop_smoke_tests'] = {}
default['hadoop_smoke_tests']['oozie_user'] = 'ubuntu'
default['hadoop_smoke_tests']['hdfs_wf_path'] = 'hdfs://Test-Laptop/user/ubuntu/oozie-smoke-tests'
default['hadoop_smoke_tests']['secure_cluster'] = true
default['hadoop_smoke_tests']['krb5_realm'] = 'BCPC.EXAMPLE.COM'
default['hadoop_smoke_tests']['rm'] = 'f-bcpc-vm2.bcpc.example.com'
default['hadoop_smoke_tests']['fs'] = 'hdfs://Test-Laptop'
default['hadoop_smoke_tests']['thrift_uris'] = 'thrift://f-bcpc-vm2.bcpc.example.com:9083'
default['hadoop_smoke_tests']['zk_quorum'] = 'f-bcpc-vm1.bcpc.example.com,f-bcpc-vm2.bcpc.example.com'
default['hadoop_smoke_tests']['hbase_master_princ'] = 'hbase/_HOST@BCPC.EXAMPLE.COM'
default['hadoop_smoke_tests']['hbase_region_princ'] = 'hbase/_HOST@BCPC.EXAMPLE.COM'
default['hadoop_smoke_tests']['hive_hmeta_princ'] = 'hive/_HOST@BCPC.EXAMPLE.COM'
default['hadoop_smoke_tests']['hive_hserver_princ'] = 'hive/_HOST@BCPC.EXAMPLE.COM'
